### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by deostroll** [Patreo/Tie.Controls.Bootstrap#1]
What sort of licence does this code have?

**Comment by pmcfernandes** [comment]
Sorry i don't published is GPL

**Comment by MarceloGiovanni** [comment]
LGPL or GPL? this makes a huge difference. GPL is basically unusable for most commercial applications.

**Comment by pmcfernandes** [comment]
Is free for all. You can change like you want, only thing i want is notify me all changes for can update in main repository.
