### ISSUE TITLE
Example page?

### ISSUE THREAD

**Issue by ghost** [Patreo/Tie.Controls.Bootstrap#2]
Do you have full items example?

**Comment by pmcfernandes** [comment]
No,  don't have. Most of controls are very simples or use ASP.net Templates for easy integration

**Comment by pexim79** [comment]
Hello,

This is a very nice project. Can you provide a sample with one of the controls. Like Alert Object.
Can we instanciate an Alert object in runtime and add it to Page? How?

Can you give me some feedback?
Thanks in advanced

**Comment by pmcfernandes** [comment]
Hi,

Thanks. Most of controls use Templates. You can basically create a <Content></Content> and put inside what you want html or other asp.net controls.

See Fieldset in https://github.com/pmcfernandes/BootstrapControls/blob/master/Samples/Login.aspx

**Comment by pexim79** [comment]
Hi Pedro,

Thanks a lot, i saw the sample of your project and could figured out.
I have another question. I was trying to use Window Control with fade effect. in my code behind i set the property 'Visible' to value 'True' but can´t see the panel.

Can you tell me how it works Window Control? And with fade effect, do i have to include some kind of jquery code in my .js file?

Can i make the Alert Control with fade effect?

Sorry to bother.
Thanks in advanced

Best regards

**Comment by pmcfernandes** [comment]
Hi

Visible = True use same Visible used in .NET Framework this means when Visible = False control will not be rendered in client. 

If you want hide this in client side you need keep Visible = True and on jquery document load you will need hide element you can get control Client ID using <%= controlname.ClientID %>

like this

$(document).ready(function() {
     $('#<%= controlname.ClientID %>').hide();
});

To user alert contol is same step. But use animate method of jquery.
